aplpromotion/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^discount\.html$', views.DiscountList.as_view(), name='DiscountList'),
	url(r'^discount/add\.html$', views.DiscountAdd.as_view(), name='DiscountAdd'),
	url(r'^discount/(?P<discount_code>[\w\-]+)/change\.html$', views.DiscountChange.as_view(), name='DiscountChange'),
	url(r'^discount/(?P<discount_code>[\w\-]+)/remove\.html$', views.DiscountRemove.as_view(), name='DiscountRemove'),
]

dms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^base/', include('aplbase.urls', namespace='aplbase')),
    url(r'^distro/', include('apldistro.urls', namespace='apldistro')),
    url(r'^inventory/', include('aplinventory.urls', namespace='aplinventory')),
    url(r'^transaction/', include('apltransaction.urls', namespace="apltransaction")),
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^billship/', include('aplbillship.urls', namespace='aplbillship')),
    url(r'^report/', include('aplreport.urls', namespace='aplreport')),
    url(r'^promotion/', include('aplpromotion.urls', namespace='aplpromotion')),
    url(r'^admin/', include(admin.site.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplpromotion/models.py
from django.db import models
from aplinventory.models import Article
from apltransaction.models import InvoiceCategory


class Discount(models.Model):
	code = models.CharField(max_length=10, unique=True)
	article = models.ForeignKey(Article)
	place = models.ForeignKey(InvoiceCategory)
	name = models.CharField(max_length=30)
	cut_price = models.PositiveIntegerField()

	class Meta:
		unique_together = ('article', 'place')

	def __str__(self):
		return self.name

aplpromotion/forms.py
from django import forms
from .models import Discount


class FormDiscountAdd(forms.ModelForm):
	class Meta:
		model = Discount
		fields = '__all__'
		exclude = ['code',]

		
class FormDiscountChange(forms.ModelForm):
	class Meta:
		model = Discount
		fields = '__all__'
		exclude = ['code',]

aplpromotion/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from aplhelper.views import helper_generate_code

from .models import Discount
from .forms import FormDiscountAdd
from .forms import FormDiscountChange


class DiscountList(View):
	template = 'aplpromotion/discount/discount_list.html'

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(DiscountList, self).dispatch(*args, **kwargs)

	def get(self, request):
		discounts = Discount.objects.all()	
		data_context = {'discounts': discounts}
		return render(request, self.template, data_context)

	def post(self, request):
		return self.get(request)


class DiscountAdd(View):
	form_discount_add = FormDiscountAdd
	template = 'aplpromotion/discount/discount_add.html'

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(DiscountAdd, self).dispatch(*args, **kwargs)

	def get(self, request):
		form = self.form_discount_add()

		data_context = {'form': form}
		return render(request, self.template, data_context)

	def post(self, request):
		form = self.form_discount_add(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.code = "DCT-" + helper_generate_code()
			instance.save()
			return HttpResponseRedirect(reverse('aplpromotion:DiscountList'))

		data_context = {'form': form}
		return render(request, self.template, data_context)


class DiscountChange(View):
	form_discount_change = FormDiscountChange
	template = 'aplpromotion/discount/discount_change.html'

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(DiscountChange, self).dispatch(*args, **kwargs)

	def get(self, request, discount_code):
		discount = get_object_or_404(Discount, code=discount_code) 
		form = self.form_discount_change(instance=discount)

		data_context = {'form': form}
		return render(request, self.template, data_context)

	def post(self, request, discount_code):
		discount = get_object_or_404(Discount, code=discount_code)
		form = self.form_discount_change(instance=discount, data=request.POST)

		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('aplpromotion:DiscountList'))

		data_context = {'form': form}
		return render(request, self.template, data_context)


class DiscountRemove(View):

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super(DiscountRemove, self).dispatch(*args, **kwargs)

	def get(self, request, discount_code):
		discount = get_object_or_404(Discount, code=discount_code)
		discount.delete()
		return HttpResponseRedirect(reverse('aplpromotion:DiscountList'))

	def post(self, request, discount_code):
		return self.get(request, discount_code)

templates/aplpromotion/discount/DiscountAdd.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Add Discount{% endblock %}

{% block heading %}Add Discount{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}
<div class="col-lg-5">
    <form action="" method="post">
        {% csrf_token %}
        
        {% if form.non_field_errors %}
            <div class="non-field-errors">
            {% for err in form.non_field_errors %}
                <p class="form-error text-danger">{{ err }}</p>
            {% endfor %}
            </div>
        {% endif %}

        <!-- ============= -->
        <!-- Article field -->
        <!-- ============= -->
        <div class="form-group">
            <label for="{{ form.article.id_for_label }}">Article :</label>
            {{ form.article|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.article.errors %}
                {% for error in form.article.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- =========== -->
        <!-- Place field -->
        <!-- =========== -->
        <div class="form-group">
            <label for="{{ form.place.id_for_label }}">Place :</label>
            {{ form.place|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.place.errors %}
                {% for error in form.place.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- ========== -->
        <!-- Name field -->
        <!-- ========== -->
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" >Name :</label>
            {{ form.name|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        
        <div class="form-group">
            <label for="{{ form.cut_price.id_for_label }}" >Cut Price :</label>
            {{ form.cut_price|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.cut_price.errors %}
                {% for error in form.cut_price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <input type="submit"  value="save" class="btn btn-success">
    </form>
</div>

{% endblock %}

{% block js %}

<script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>

<script>
$(document).ready(function(){
    $('.selectpicker').selectpicker();
});
</script>
{% endblock %}

templates/aplpromotion/discount/DiscountChange.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Discount{% endblock %}

{% block heading %}Discount{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}
<div class="col-lg-5">
    <form action="" method="post">
        {% csrf_token %}
        
        {% if form.non_field_errors %}
            <div class="non-field-errors">
            {% for err in form.non_field_errors %}
                <p class="form-error text-danger">{{ err }}</p>
            {% endfor %}
            </div>
        {% endif %}

        <!-- ============= -->
        <!-- Article field -->
        <!-- ============= -->
        <div class="form-group">
            <label for="{{ form.article.id_for_label }}">Article :</label>
            {{ form.article|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.article.errors %}
                {% for error in form.article.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- =========== -->
        <!-- Place field -->
        <!-- =========== -->
        <div class="form-group">
            <label for="{{ form.place.id_for_label }}">Place :</label>
            {{ form.place|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.place.errors %}
                {% for error in form.place.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- ========== -->
        <!-- Name field -->
        <!-- ========== -->
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" >Name :</label>
            {{ form.name|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        
        <div class="form-group">
            <label for="{{ form.cut_price.id_for_label }}" >Cut Price :</label>
            {{ form.cut_price|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.cut_price.errors %}
                {% for error in form.cut_price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <input type="submit"  value="save" class="btn btn-success">
    </form>
</div>

{% endblock %}

{% block js %}

<script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>

<script>
$(document).ready(function(){
    $('.selectpicker').selectpicker();
});
</script>
{% endblock %}

templates/aplpromotion/discount/DiscountList.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Discount{% endblock %}

{% block heading %}Discount{% endblock %}



{% block content %}
<div class="col-md-6">
	<a href="{% url 'aplpromotion:DiscountAdd' %}" class="btn btn-default"><i class="fa fa-plus"></i> add new
	</a>
</div>	

<br><br>

<div class="col-md-12">
	<table class="table table-striped table-condensed">
		<tr>
			<th>#</th>
			<th>Article</th>
			<th>Place</th>
			<th>Name</th>
			<th>Cut Price</th>
			<th>Action</th>
		</tr>
		{% for discount in discounts %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ discount.article.name }}</td>
			<td>{{ discount.place.info }}</td>
			<td>{{ discount.name }}</td>
			<td>{{ discount.cut_price }}</td>
			<td>
				<a href="{% url 'aplpromotion:DiscountChange' discount.code %}">change</a> |
				<a href="{% url 'aplpromotion:DiscountRemove' discount.code %}">remove</a>
			</td>
		</tr>
		{% empty %}
		<tr>
			<td colspan="6">Empty</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

templates/aplpromotion/discount/discount_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Add Discount{% endblock %}

{% block heading %}Add Discount{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}
<div class="col-lg-5">
    <form action="" method="post">
        {% csrf_token %}
        
        {% if form.non_field_errors %}
            <div class="non-field-errors">
            {% for err in form.non_field_errors %}
                <p class="form-error text-danger">{{ err }}</p>
            {% endfor %}
            </div>
        {% endif %}

        <!-- ============= -->
        <!-- Article field -->
        <!-- ============= -->
        <div class="form-group">
            <label for="{{ form.article.id_for_label }}">Article :</label>
            {{ form.article|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.article.errors %}
                {% for error in form.article.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- =========== -->
        <!-- Place field -->
        <!-- =========== -->
        <div class="form-group">
            <label for="{{ form.place.id_for_label }}">Place :</label>
            {{ form.place|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.place.errors %}
                {% for error in form.place.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- ========== -->
        <!-- Name field -->
        <!-- ========== -->
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" >Name :</label>
            {{ form.name|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        
        <div class="form-group">
            <label for="{{ form.cut_price.id_for_label }}" >Cut Price :</label>
            {{ form.cut_price|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.cut_price.errors %}
                {% for error in form.cut_price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <input type="submit"  value="save" class="btn btn-success">
    </form>
</div>

{% endblock %}

{% block js %}

<script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>

<script>
$(document).ready(function(){
    $('.selectpicker').selectpicker();
});
</script>
{% endblock %}

templates/aplpromotion/discount/discount_change.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Discount{% endblock %}

{% block heading %}Discount{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
{% endblock %}

{% block content %}
<div class="col-lg-5">
    <form action="" method="post">
        {% csrf_token %}
        
        {% if form.non_field_errors %}
            <div class="non-field-errors">
            {% for err in form.non_field_errors %}
                <p class="form-error text-danger">{{ err }}</p>
            {% endfor %}
            </div>
        {% endif %}

        <!-- ============= -->
        <!-- Article field -->
        <!-- ============= -->
        <div class="form-group">
            <label for="{{ form.article.id_for_label }}">Article :</label>
            {{ form.article|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.article.errors %}
                {% for error in form.article.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- =========== -->
        <!-- Place field -->
        <!-- =========== -->
        <div class="form-group">
            <label for="{{ form.place.id_for_label }}">Place :</label>
            {{ form.place|add_class:'form-control selectpicker'|attr:'data-show-subtext:true'|attr:'data-live-search:true' }}
            {% if form.place.errors %}
                {% for error in form.place.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <!-- ========== -->
        <!-- Name field -->
        <!-- ========== -->
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}" >Name :</label>
            {{ form.name|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        
        <div class="form-group">
            <label for="{{ form.cut_price.id_for_label }}" >Cut Price :</label>
            {{ form.cut_price|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.cut_price.errors %}
                {% for error in form.cut_price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <input type="submit"  value="save" class="btn btn-success">
    </form>
</div>

{% endblock %}

{% block js %}

<script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.min.js' %}"></script>

<script>
$(document).ready(function(){
    $('.selectpicker').selectpicker();
});
</script>
{% endblock %}

templates/aplpromotion/discount/discount_list.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Discount{% endblock %}

{% block heading %}Discount{% endblock %}



{% block content %}
<div class="col-md-6">
	<a href="{% url 'aplpromotion:DiscountAdd' %}" class="btn btn-default"><i class="fa fa-plus"></i> add new
	</a>
</div>	

<br><br>

<div class="col-md-12">
	<table class="table table-striped table-condensed">
		<tr>
			<th>#</th>
			<th>Article</th>
			<th>Place</th>
			<th>Name</th>
			<th>Cut Price</th>
			<th>Action</th>
		</tr>
		{% for discount in discounts %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ discount.article.name }}</td>
			<td>{{ discount.place.info }}</td>
			<td>{{ discount.name }}</td>
			<td>{{ discount.cut_price }}</td>
			<td>
				<a href="{% url 'aplpromotion:DiscountChange' discount.code %}">change</a> |
				<a href="{% url 'aplpromotion:DiscountRemove' discount.code %}">remove</a>
			</td>
		</tr>
		{% empty %}
		<tr>
			<td colspan="6">Empty</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}