apltransaction/urls.py
from django.conf.urls import url
from . import views, ajax_views

urlpatterns = [

    url(r'^ajax/invoice/remove/hold/invalid\.html', views.ajax_invoice_remove_hold_and_invalid, name='ajax_invoice_remove_hold_and_invalid'),

    # Invoice Store URL
    url(r'^invoice/store\.html$', views.invoicestore_list, name='invoicestore_list'),
    url(r'^invoice/store/add\.html$', views.invoicestore_add, name='invoicestore_add'),
    url(r'^invoice/store/(?P<invoice_number>[\w\-]+)/print\.html$', views.invoicestore_print, name='invoicestore_print'),
    url(r'^invoice/store/(?P<invoice_number>[\w\-]+)/remove\.html$', views.invoicestore_remove, name='invoicestore_remove'),
    
    # Transaction Store URL
    url(r'^transdetail/store/(?P<invoice_number>[\w\-]+)/add\.html$', views.transactiondetailstore_add, name='transactiondetailstore_add'),
    url(r'^transdetail/store/(?P<invoice_number>[\w\-]+)/(?P<article_code>[\w\-]+)/remove\.html$', views.transactiondetailstore_remove, name='transactiondetailstore_remove'),

    # Invoice Web URL
    url(r'^invoice/web\.html$', views.invoiceweb_list, name='invoiceweb_list'),
    url(r'^ajax/invoice/web\.html$', ajax_views.AjaxInvoiceWebList.as_view(), name='ajax_invoice_web_list'),
    url(r'^invoice/web/add\.html$', views.invoiceweb_add, name='invoiceweb_add'),
    url(r'^invoice/web/(?P<invoice_number>[\w\-]+)/remove\.html$', views.invoiceweb_remove, name='invoiceweb_remove'),
    url(r'^invoice/web/(?P<invoice_number>[\w\-]+)/print\.html$', views.invoiceweb_print, name='invoiceweb_print'),
    url(r'^invoice/web/(?P<invoice_number>[\w\-]+)/changestatus\.html$', views.invoiceweb_changestatus, name='invoiceweb_changestatus'),
    url(r'^invoice/web/print/all\.html$', views.invoiceweb_print_all, name="invoiceweb_print_all"),
    url(r'^invoice/web/change/status/process\.html', views.invoiceweb_change_status_process, name='invoiceweb_change_status_process'),
    url(r'^invoice/web/change/status/ready\.html', views.invoiceweb_change_status_ready, name="invoiceweb_change_status_ready"),
    url(r'^invoice/web/change/status/pending\.html', views.invoiceweb_change_status_pending, name="invoiceweb_change_status_pending"),
    url(r'^invoice/web/change/status/finish\.html', views.invoiceweb_change_status_finish, name="invoiceweb_change_status_finish"),
    url(r'^invoice/web/change/status/cancel\.html', views.invoiceweb_change_status_cancel, name="invoiceweb_change_status_cancel"),
    
    # ==========================
    # Transaction Detail Web URL
    # ==========================
    url(r'^transdetail/web/(?P<invoice_number>[\w\-]+)/add\.html$', views.transactiondetailweb_add, name='transactiondetailweb_add'),
    url(r'^transdetail/web/(?P<invoice_number>[\w\-]+)/(?P<article_code>[\w\-]+)/remove\.html$', views.transactiondetailweb_remove, name='transactiondetailweb_remove'),


]

dms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^base/', include('aplbase.urls', namespace='aplbase')),
    url(r'^distro/', include('apldistro.urls', namespace='apldistro')),
    url(r'^inventory/', include('aplinventory.urls', namespace='aplinventory')),
    url(r'^transaction/', include('apltransaction.urls', namespace="apltransaction")),
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^billship/', include('aplbillship.urls', namespace='aplbillship')),
    url(r'^report/', include('aplreport.urls', namespace='aplreport')),
    url(r'^promotion/', include('aplpromotion.urls', namespace='aplpromotion')),
    url(r'^admin/', include(admin.site.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apltransaction/models.py
from django.db import models
from apldistro.models import Brand
from aplinventory.models import ArticleDetail
import datetime

class InvoiceCategory(models.Model):
    abbv = models.CharField(max_length=2)
    info = models.CharField(max_length=30)

    def __str__(self):
        return self.abbv


class InvoiceStatus(models.Model):
    abbv = models.CharField(max_length=2)
    info = models.CharField(max_length=30)

    def __str__(self):
        return self.abbv


class Invoice(models.Model):
    user = models.ForeignKey('auth.User')
    invoice_number = models.CharField(max_length=10, unique=True)
    invoice_date = models.DateField(default=datetime.date.today)
    total = models.PositiveIntegerField()
    category = models.ForeignKey(InvoiceCategory)
    status = models.ForeignKey(InvoiceStatus)

    def __str__(self):
        return self.invoice_number


class TransactionDetail(models.Model):
    user = models.ForeignKey('auth.User')
    invoice = models.ForeignKey(Invoice)

    article_brand_code = models.CharField(max_length=30)
    article_brand_name = models.CharField(max_length=100)
    article_code = models.CharField(max_length=200)
    article_name = models.CharField(max_length=200)
    article_size = models.CharField(max_length=50)
    article_price = models.PositiveIntegerField()
    article_capitalprice = models.PositiveIntegerField()

    quantity = models.PositiveIntegerField()
    sub_total = models.PositiveIntegerField()
    
    ################ DISCOUNT AREA #########################################
    discount_code = models.CharField(max_length=100, blank=True, null=True)
    discount_name = models.CharField(max_length=30, blank=True, null=True)
    cut_price = models.PositiveIntegerField(blank=True, null=True)
    ########################################################################

    def __str__(self):
        return self.invoice.invoice_number

    class Meta:
        unique_together = ('invoice', 'article_size', 'article_code')

apltransaction/forms.py
from django import forms
from .models import Invoice, TransactionDetail


class FormAddTransactionDetail(forms.ModelForm):
    class Meta:
        model = TransactionDetail
        fields = ('article_code', 'article_name', 'article_size',
                  'article_price', 'quantity', 'sub_total')


class FormAddTransactionStoreDetail(forms.ModelForm):
	class Meta:
		model = TransactionDetail
		fields = ('article_code',)


class FormAddTransactionWebDetail(forms.ModelForm):
    class Meta:
        model = TransactionDetail
        fields = ('article_code', 'article_name', 'article_size',
                  'article_price', 'quantity', 'sub_total')


class FormSearchInvoice(forms.Form):
    query = forms.CharField()


class FormInvoiceWebChangeStatus(forms.ModelForm):
  class Meta:
    model = Invoice
    fields = ('status',)

apltransaction/views.py
# ======================
# Built-in Python module
# ======================
from datetime import date
import json

# ==================
# Django part module
# ==================
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.db import IntegrityError, transaction as trans
from django.contrib import messages
from django.db.models import Sum, PositiveIntegerField, Q, F
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import transaction as trans
from django.views.generic import View

# ================
# Inner app module
# ================
from .models import Invoice
from .models import TransactionDetail 
from .models import InvoiceCategory
from .models import InvoiceStatus
from .forms import FormAddTransactionDetail
from .forms import FormAddTransactionStoreDetail
from .forms import FormSearchInvoice
from .forms import FormAddTransactionWebDetail
from .forms import FormInvoiceWebChangeStatus

# ====================
# aplhelper app module
# ====================
from aplhelper.helpers import helper_generate_code, helper_session_brand_pk
from common.decorators import connecting_brand_required
from aplpromotion.models import Discount

# =======================
# aplinventory app module
# =======================
# from aplinventory.models import BrandArticleDetail, Article
from aplinventory.views import helper_generate_code
from aplinventory.models import ArticleDetail, Article

from apldistro.models import Profile, Store, Brand
from aplbillship.models import Billing, Shipping
from apltransaction.models import InvoiceStatus

# ===================
# dataresource module
# ===================
from dataresource.models import HoldTarget



## =============================================================================
##                                  INVOICE (GENERAL)
## =============================================================================

def ajax_invoice_remove_hold_and_invalid(request):
    if request.is_ajax():
        total_invoices_invalid = 0
        total_article_back = 0
        total_invoices_cancel = 0

        if request.method == 'POST':
            try:
                # mendapatkan data dari ajax post dan merubah ke json string format utf-8
                json_string = request.body.decode(encoding='UTF-8')
                # merubah string json ke dictionary python
                dict_data = json.loads(json_string)

                # ambil semua data invoice yang tidak ada item transactiondetail-nya.
                invoices_invalid = Invoice.objects.filter(transactiondetail=None)
                print(invoices_invalid)
                total_invoices_invalid = invoices_invalid.count()
                if invoices_invalid.count() > 0:
                    invoices_invalid.delete()
            except:
                pass

            try:
                # ambil semua data invoice yang tidak ada shipping yang berlaku untuk web
                invoices_nobill = Invoice.objects.filter(billing=None, category__abbv='W')
                # hapus data
                for inv in invoices_nobill:
                    if inv.transactiondetail_set.count() == 0:
                        inv.delete()
                    elif inv.transactiondetail_set.count() > 0:
                        # mengupdate stock article detail dari quantity pda transaction detail
                        for td in inv.transactiondetail_set.all():
                            articledetail = ArticleDetail.objects.get(
                                code=td.article_code)
                            stock = articledetail.stock
                            articledetail.stock = stock + td.quantity
                            articledetail.save()
                            total_article_back += 1

                        inv.delete()
            except:
                pass

            try:
                # ambil semua data invoice yang tidak ada billing yang berlaku untuk web
                invoices_noshipp = Invoice.objects.filter(shipping=None, category__abbv='W')
                # hapus data
                for inv in invoices_noshipp:
                    if inv.transactiondetail_set.count() == 0:
                        inv.delete()
                    elif inv.transactiondetail_set.count() > 0:
                        # mengupdate stock article detail dari quantity pda transaction detail
                        for td in inv.transactiondetail_set.all():
                            articledetail = ArticleDetail.objects.get(
                                code=td.article_code)
                            stock = articledetail.stock
                            articledetail.stock = stock + td.quantity
                            articledetail.save()
                            total_article_back += 1

                        inv.delete()
            except:
                pass

            try:
                # ambil semua data invoice yang statusnya hold
                invoices_hold = Invoice.objects.filter(status__abbv='H', category__abbv='W')
                # hapus data
                for inv in invoices_hold:
                    if inv.transactiondetail_set.count() == 0:
                        inv.delete()
                    elif inv.transactiondetail_set.count() > 0:
                        # mengupdate stock article detail dari quantity pda transaction detail
                        for td in inv.transactiondetail_set.all():
                            articledetail = ArticleDetail.objects.get(
                                code=td.article_code)
                            stock = articledetail.stock
                            articledetail.stock = stock + td.quantity
                            articledetail.save()
                            total_article_back += 1

                        status = InvoiceStatus.objects.filter(abbv='C')
                        if status.exists():
                            inv.status = status[0]
                            total_invoices_cancel += 1
                            print("nah kan")
                            inv.save()
                        else:
                            inv.delete()
            except:
                pass

            
            dict_data = {
                'total_invoices_invalid': total_invoices_invalid,
                'total_article_back': total_article_back,
                'total_invoices_cancel': total_invoices_cancel
            }
            
            return HttpResponse(json.dumps(dict_data), content_type='application/json')

        else:
            return HttpResponse(json.dumps({'status': False}), content_type='application/json')
    else:
        return render(request, 'apltransaction/invoice/ajax_invoice_remove_hold_and_invalid.html', {})




## =============================================================================
##                                  INVOICE STORE                                       
## =============================================================================


def invoicestore_list(request):
    invoices = Invoice.objects.filter(category__abbv='S').exclude(Q(transactiondetail=None)).order_by('-invoice_date')
    # invoices = Invoice.objects.filter(category__abbv='S').exclude(Q(transactiondetail=None)).order_by('-invoice_date')
    form = FormSearchInvoice()

    # =================================
    # Pencarian invoice dari input text 
    # =================================
    if 'query' in request.GET:
        form = FormSearchInvoice(request.GET)

        if form.is_valid():
            cd = form.cleaned_data
            invoices = invoices.filter(
                Q(invoice_number__icontains=cd['query']) | 
                Q(user__username__icontains=cd['query']) | 
                Q(transactiondetail__article_name__icontains=cd['query']) | 
                Q(category__abbv__icontains=cd['query'][0])).distinct()

    # =================================================
    # Filter invoice dari tombol filter (Version 1.0.0)
    # =================================================
    if 'status' in request.GET:
        data_status = request.GET.get('status')
        invoicestatus = get_object_or_404(InvoiceStatus, abbv=data_status)
        invoices = invoices.filter(status=invoicestatus)

    # ================================
    # Paginasi halaman (Version 1.0.0)
    # ================================
    paginator = Paginator(invoices, 7)
    page = request.GET.get('page')
    try:
        invoices = paginator.page(page)
    except PageNotAnInteger:
        invoices = paginator.page(1)
    except EmptyPage:
        invoices = paginator.page(paginator.num_pages)

    data_context = {'invoices': invoices, 'form': form, 'total_count': invoices}
    return render(request, 'apltransaction/invoice/invoicestore_list.html', 
        data_context)


def invoicestore_add(request):
    invoicecategory = get_object_or_404(InvoiceCategory, abbv='S')

    invoicestatus = get_object_or_404(InvoiceStatus, abbv='F')

    invoice = Invoice(user=request.user, invoice_number=helper_generate_code(),
        total=0, category=invoicecategory, status=invoicestatus)
    invoice.save()

    return HttpResponseRedirect(
        reverse('apltransaction:transactiondetailstore_add', 
            kwargs={'invoice_number': invoice.invoice_number}))


def invoicestore_remove(request, invoice_number):
    invoice = get_object_or_404(Invoice, invoice_number=invoice_number)

    if invoice.transactiondetail_set.count() > 0:
        for item in invoice.transactiondetail_set.all():
            try:
                article = ArticleDetail.objects.get(code=item.article_code)
                stock_article = article.stock
                article.stock = stock_article + item.quantity
                article.save()

templates/apltransaction/invoice/ajax_invoice_remove_hold_and_invalid.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Remove All Invoice Hold & Invalid{% endblock %}

{% block heading %}Remove All Invoice Hold & Invalid{% endblock %}

{% block content %}
<div class="col-md-4">
    <p class="text-danger">
        be sure to perform this action. This action will remove all the invoicing data that have invalid status and hold.
    </p>
    <button id="id_ajax_invoice_remove_hold_and_invalid" class="btn btn-danger btn-lg btn-block">clean invoice in hold & invalid !</button>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Success</h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
    $(document).ready(function() {
        $('input:checkbox[name=action_toggle]').change(function() {
            $('input:checkbox[name=_selected_action]').not(this).prop('checked', this.checked);
        });

        $('#id_invoiceweb_print_all').click(function() {
            $("#id_form_invoiceweb_print_all").submit();
        });

        $('#id_invoiceweb_change_status_process').click(function() {
            $('#id_form_invoiceweb_print_all').attr('action', '{% url 'apltransaction:invoiceweb_change_status_process' %}').submit();
        });

        $("#id_ajax_invoice_remove_hold_and_invalid").on('click', function() {
            $.ajax({
                url: "{% url 'apltransaction:ajax_invoice_remove_hold_and_invalid' %}",
                dataType: 'json',
                method: 'POST',
                data: JSON.stringify({'hallo': 'Hallo Yanwar'}),
                contentType: 'application/json',
                success: function(data) {

                    var dataHtml = "<ul>"; 
                        dataHtml += "<li>Total article back to warehouse: " + data.total_article_back + "</li>";
                        dataHtml += "<li>Total invalid invoice: " + data.total_invoices_invalid + "</li>";
                        dataHtml += "<li>Total cancel invoice: " + data.total_invoices_cancel + "</li>";
                        dataHtml += "</ul>";

                    $(".modal-body").html('success removing invalid and hold invoice ! <hr>' + dataHtml);
                    $('#myModal').modal('show');

                },
                error: function() {

                }
            });
            return false;
        });
    });
</script>
{% endblock %}

templates/apltransaction/invoice/invoicestore_list.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}Invoice In{% endblock %}

{% block heading %}Invoice Store{% endblock %}

{% block content %}
<div class="col-md-6">
    <!-- Split button -->
    <a href="{% url 'apltransaction:invoicestore_add' %}" class="btn btn-default"><i class="fa fa-plus"></i> add new</a>
</div>

<div class="col-md-6">
    <form action="" method="get">
        {{ form.query|add_class:"form-control"|attr:"placeholder:Search Invoice" }}
    </form>
</div>

<div class="col-lg-12">
    <br>
        <form method="post" action="{% url 'apltransaction:invoiceweb_print_all' %}" id="id_form_invoiceweb_print_all">
        {% csrf_token %}
        <table class="table table-condensed table-bordered">
            <tr>
                <th><input type="checkbox" name="action_toggle"></th>
                <th>#</th>
                <th>User</th>
                <th>Invoice Number</th>
                <th>Date Transaction</th>
                <th>Total Price</th>
                <th>Category</th>
                <th>Status</th>
                <th>Detail</th>
            </tr>
            {% for invoice in invoices %}
                <tr>
                    <td><input type="checkbox" id="id_selected_action" name="_selected_action" value="{{ invoice.invoice_number }}"></td>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ invoice.user.username }}</td>
                    <td>{{ invoice.invoice_number }}</td>
                    <td>{{ invoice.invoice_date }}</td>
                    <td>{{ invoice.total }}</td>
                    <td>{{ invoice.category.info }}</td>
                    <td>{{ invoice.status.info }}</td>
                    <td>
                        <!-- MODAL TRIGGER DETAIL INVOICE -->
                        <a data-toggle="modal" href="#{{ invoice.invoice_number }}">
                            detail
                        </a>

                        <!-- MODAL DETAIL INVOICE -->
                        <div class="modal fade bs-example-modal-lg" id="{{ invoice.invoice_number }}">
                        	<div class="modal-dialog modal-lg">
                        		<div class="modal-content">
                        			<div class="modal-header">
                        				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

                        				<h4 class="modal-title">
                                            Invoice #{{ invoice.invoice_number }} ({{ invoice.status.info }})
                                        </h4>
                        			</div>
                        			<div class="modal-body">
                                        <div class="well well-samll">
                                            Grand Total: <strong>IDR. {{ invoice.total }}</strong>
                                        </div>
                        				<table class="table table-bordered">
                                            <tr>
                                                <th class="text-center" colspan="6">Article In Bag</th>
                                            </tr>
                                            <tr>
                                                <th>#</th>
                                                <th>Article</th>
                                                <th>Size</th>
                                                <th>Price</th>
                                                <th>Quantity</th>
                                                <th>Sub Total</th>
                                            </tr>
                                            {% for item in invoice.transactiondetail_set.all %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ item.article_name }}</td>
                                                    <td>{{ item.article_size }}</td>
                                                    <td>{{ item.article_price }}</td>
                                                    <td>{{ item.quantity }}</td>
                                                    <td>{{ item.sub_total }}</td>
                                                </tr>
                                            {% endfor %}
                                        </table>

                                        {% if invoice.category.abbv == 'W' %}
                                            {# BILLING #}
                                            <table class="table table-bordered">
                                                <tr>
                                                    <th class="text-center" colspan="4">Billing</th>
                                                </tr>
                                                <tr>
                                                    <th>Code</th>
                                                    <th>Name</th>
                                                    <th>Email</th>
                                                    <th>Phone</th>
                                                </tr>
                                                {% for bill in invoice.billing_set.all %}
                                                    <tr>
                                                        <td>{{ bill.code}}</td>
                                                        <td>{{ bill.name }}</td>
                                                        <td>{{ bill.email }}</td>
                                                        <td>{{ bill.phone }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </table>
                                            {# SHIPPING #}
                                            <table class="table table-bordered">
                                                <tr>
                                                    <th class="text-center" colspan="6">Shipping</th>
                                                </tr>
                                                <tr>
                                                    <th>Code</th>
                                                    <th>Province</th>
                                                    <th>City</th>
                                                    <th>Vendor / Courier</th>
                                                    <th>Package</th>
                                                    <th>Price</th>
                                                </tr>
                                                {% for ship in invoice.shipping_set.all %}
                                                    <tr>
                                                        <td>{{ ship.code}}</td>
                                                        <td>{{ ship.province }}</td>
                                                        <td>{{ ship.city }}</td>
                                                        <td>{{ ship.vendor }}</td>
                                                        <td>{{ ship.pack }}</td>
                                                        <td>{{ ship.price }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </table>
                                        {% else %}
                                        {% endif %}
                        			</div>

                        			<div class="modal-footer">
                                        {% if invoice.category.abbv == 'W' %}
                                        <a class="btn btn-default" href="{% url 'apltransaction:transactiondetailweb_add' invoice.invoice_number %}">
                                            open
                                        </a>
                                        <a class="btn btn-default" href="{% url 'apltransaction:invoiceweb_print' invoice.invoice_number %}">
                                            print
                                        </a>
                                        {% else %}
                                        <a class="btn btn-default" href="{% url 'apltransaction:transactiondetailstore_add' invoice.invoice_number %}">
                                            open
                                        </a>
                                        <a class="btn btn-default" href="{% url 'apltransaction:invoicestore_print' invoice.invoice_number %}">
                                            print
                                        </a>
                                        {% endif %}
                        			</div>
                        		</div><!-- /.modal-content -->
                        	</div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="9"><p>There has been no transaction.</p></td>
                </tr>
            {% endfor %}
        </table>
        </form>
    {% include "apltransaction/invoice/pagination.html" with page=invoices %}
</div>

{% endblock %}


{% block js %}
<script type="text/javascript">
$(document).ready(function() {
    $('input:checkbox[name=action_toggle]').change(function() {
        $('input:checkbox[name=_selected_action]').not(this).prop('checked', this.checked);
    });

    $('#id_invoiceweb_print_all').click(function() {
        $("#id_form_invoiceweb_print_all").submit();
    });

    $('#id_invoiceweb_change_status_process').click(function() {
        $('#id_form_invoiceweb_print_all').attr('action', '{% url 'apltransaction:invoiceweb_change_status_process' %}').submit();
    });
});
</script>
{% endblock %}

templates/apltransaction/invoice/invoicestore_print.html

{% load thumbnail %}



<style type="text/css" media="all">
    * {
        font-size: 8pt;
        font-family: monospace;
    }
    td {
        font-size: 8pt;

    }
</style>

<style type="text/css" media="print">
    * {
        font-size: 8pt;
        font-family: monospace;
    }
    td {
        font-size: 8pt;

    }

    a {
        display: none;
    }

    h3 {
        font-size: 12pt;
    }

    img {
        opacity: 20;
    }

    small   {
        font-size: 7pt;
    }

    hr {
        padding: 0;
        margin: 0;
    }
</style>
{% block content_billing %}
<h1><center>EFG Store</center></h1>
<p><center>{{ store.address }}</center></p>


NUMBER #{{ invoice.invoice_number }} <br>
TANGGAL: {{ invoice.invoice_date }}
<br>
BY: {{ invoice.user }}
<br><br><hr>
<table class="table table-bordered table-condensed">
    {% for item in transactiondetails %}
    <tr>
        <td valign="top">{{ forloop.counter }}</td>
        <td valign="top">{{ item.article_name }} ({{ item.article_size }})</td>
        <td valign="top">{{ item.article_price }} <hr>
        {% if item.discount_code %}
            <small>
                <br> Discount 
                <br> {{ item.discount_name }} ({{ item.cut_price }}) per item
            </small>
        {% endif %}
        </td>
        <td valign="top">@ {{ item.quantity }}</td>
        <td valign="top">{{ item.sub_total }}</td>
    </tr>
    {% endfor %} 
</table>
<br>
<hr>
Grand Total: 
<h3>IDR {{ invoice.total }}</h3>

<br>
Thank You<br> See You
{% endblock %}


{% block additional_button %}
<a href="{% url 'apltransaction:invoicestore_list' %}" class="btn btn-default">Back To Invoice</a> <br><br>
{% endblock %}

{% block script %}
<script type="text/javascript">
    window.print();
</script>
{% endblock %}