aplinventory/urls.py
from django.conf.urls import url
from . import views
from . import views_popup
from . import urls_ajax

urlpatterns = [

    # SizeType URL
    url(r'^sizecategory\.html$', views.SizeCategoryList.as_view(), name='sizecategory_list'),
    url(r'^sizecategory/add\.html$', views.SizeCategoryAdd.as_view(), name='sizecategory_add'),
    url(r'^sizecategory/(?P<size_category_pk>[0-9]+)/change\.html$', views.SizeCategoryChange.as_view(), name='sizecategory_change'),
    url(r'^sizecategory/(?P<size_category_pk>[0-9]+)/remove\.html$', views.SizeCategoryRemove.as_view(), name='sizecategory_remove'),

    # # Size URL
    url(r'size\.html$', views.size_list, name='size_list'),
    url(r'size/(?P<pk_sizecategory>[0-9]+)/add\.html$', views.size_add, name='size_add'),
    url(r'size/(?P<pk_size>[0-9]+)/change\.html$', views.size_change, name='size_change'),
    url(r'size/(?P<pk_size>[0-9]+)/removed\.html$', views.size_remove, name='size_remove'),

    # Product Category URL
    url(r'^productcategory/$', views.productcategory_list, name='productcategory_list'),
    url(r'^productcategory/add/$', views.productcategory_add, name='productcategory_add'),
    url(r'^productcategory/(?P<pk_productcategory>[0-9]+)/change/$', views.productcategory_change, name='productcategory_change'),
    url(r'^productcategory/(?P<pk_productcategory>[0-9]+)/remove/$', views.productcategory_remove, name='productcategory_remove'),

    # Product URL
    url(r'^product/$', views.product_list, name='product_list'),
    url(r'^product/add/$', views.product_add, name='product_add'),
    url(r'^product/(?P<code_product>[\w\-]+)/change/$', views.product_change, name='product_change'),
    url(r'^product/(?P<code_product>[\w\-]+)/remove/$', views.product_remove, name='product_remove'),

    # Article URL
    url(r'^article/$', views.article_list, name='article_list'),
    url(r'^article/add/$', views.article_add, name='article_add'),
    url(r'^article/(?P<pk_article>[0-9]+)/change/$', views.article_change, name='article_change'),
    url(r'^article/(?P<pk_article>[0-9]+)/remove/$', views.article_remove, name='article_remove'),
    url(r'^article/(?P<pk_article>[0-9]+)/keep/$', views.article_keep, name='article_keep'),
    url(r'^article/(?P<code>[\w\-]+)/print/barcode.pdf/$', views.article_printbarcode, name='article_printbarcode'),
    
    # ArticleDetail URL
    url(r'^articledetail/(?P<pk_article>[0-9]+)/(?P<pk_sizecategory>[0-9]+)/add/$',
        views.articledetail_add, name='articledetail_add'),
    url(r'^articledetail/(?P<pk_article>[0-9]+)/(?P<pk_articledetail>[0-9]+)/change/$', 
        views.articledetail_change, name='articledetail_change'),
    url(r'^articledetail/(?P<code>[\w\-]+)/remove/$',
        views.articledetail_remove, name='articledetail_remove'),

    # ArticleDetail Popup URL
    url(r'^popup/articledetail/', views_popup.articledetail_list_popup, name='articledetail_list_popup'),

    #
    # # ArticleDetail POPUP URL
    # url(r'articledetail/popup/$', views.articledetail_list_popup, name='articledetail_list_popup'),
]

dms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^base/', include('aplbase.urls', namespace='aplbase')),
    url(r'^distro/', include('apldistro.urls', namespace='apldistro')),
    url(r'^inventory/', include('aplinventory.urls', namespace='aplinventory')),
    url(r'^transaction/', include('apltransaction.urls', namespace="apltransaction")),
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^billship/', include('aplbillship.urls', namespace='aplbillship')),
    url(r'^report/', include('aplreport.urls', namespace='aplreport')),
    url(r'^promotion/', include('aplpromotion.urls', namespace='aplpromotion')),
    url(r'^admin/', include(admin.site.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplinventory/models.py
from django.db import models
from apldistro.models import Brand


class SizeCategory(models.Model):
    user = models.ForeignKey('auth.User')
    brand = models.ForeignKey(Brand)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    class Meta:
        unique_together = ('brand', 'name')


class Size(models.Model):
    user = models.ForeignKey('auth.User')
    brand = models.ForeignKey(Brand)
    size_category = models.ForeignKey(SizeCategory)
    name = models.CharField(max_length=5)

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        unique_together = ('name', 'size_category', 'brand')


class ProductCategory(models.Model):
    user = models.ForeignKey('auth.User')
    brand = models.ForeignKey(Brand)
    sizecategory = models.ForeignKey(SizeCategory)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Product(models.Model):
    user = models.ForeignKey('auth.User')
    brand = models.ForeignKey(Brand)
    code = models.CharField(max_length=5, unique=True)
    product_category = models.ForeignKey(ProductCategory)
    name = models.CharField(max_length=30)

    def __str__(self):
        return "{} - {}".format(self.name, self.brand.name)


class Article(models.Model):
    user = models.ForeignKey('auth.User')
    brand = models.ForeignKey(Brand)
    product = models.ForeignKey(Product)
    code = models.CharField(max_length=5, unique=True, blank=True)
    name = models.CharField(max_length=50)
    capital_price = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    keep = models.BooleanField(default=False)

    def __str__(self):
        return "({}) - {}".format(self.code, self.name)


class ArticleDetail(models.Model):
    user = models.ForeignKey('auth.User')
    brand = models.ForeignKey(Brand)
    article = models.ForeignKey(Article)
    size = models.ForeignKey(Size)
    code = models.CharField(max_length=5, unique=True)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return "({}) - {}".format(self.code, self.article.name)

    class Meta:
        unique_together = ('article', 'size')


class Photo(models.Model):
    user = models.ForeignKey('auth.User')
    brand = models.ForeignKey(Brand)
    article = models.ForeignKey(Article)
    picture = models.ImageField(upload_to='aplinventory/article')

    def __str__(self):
        return self.article.name

aplinventory/views.py
# Python package import
from uuid import uuid4
# Django package import
from django.contrib import messages
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.db.models import Count
from django.db.models import Avg
from django.db.models import Q
from django.db import IntegrityError
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# This app import
from .models import SizeCategory
from .models import Size
from .models import ProductCategory
from .models import Product
from .models import Article
from .models import ArticleDetail
from .forms import FormSizeCategoryAdd
from .forms import FormSizeCategoryChange
from .forms import FormAddSize
from .forms import FormChangeSize
from .forms import FormAddProductCategory
from .forms import FormChangeProductCategory
from .forms import FormAddProduct
from .forms import FormChangeProduct
from .forms import FormAddArticle
from .forms import FormChangeArticle
from .forms import FormAddArticleDetail
from .forms import FormChangeArticleDetail
from .forms import FormSearchProduct
# aplhelper import
from aplhelper.helpers import helper_generate_code
from aplhelper.helpers import helper_session_brand_pk
# apldistro import
from apldistro.models import Brand
# common import
from common.decorators import connecting_brand_required

class SizeCategoryList(View):
    data_context = {}
    template = 'aplinventory/sizecategory/sizecategory_list.html'

    @method_decorator(login_required)
    @method_decorator(connecting_brand_required)
    def dispatch(self, *args, **kwargs):
        return super(SizeCategoryList, self).dispatch(*args, **kwargs)

    def get(self, request):
        sizecategories = SizeCategory.objects.all()
        self.data_context = {'sizecategories': sizecategories}
        return render(request, self.template, self.data_context)


class SizeCategoryAdd(View):
    form_size_category_add = FormSizeCategoryAdd
    data_context = {}
    template = 'aplinventory/sizecategory/sizecategory_add.html'

    @method_decorator(login_required)
    @method_decorator(connecting_brand_required)
    def dispatch(self, *args, **kwargs):
        return super(SizeCategoryAdd, self).dispatch(*args, **kwargs)

    def get(self, request):
        brand = helper_session_brand_pk(request)
        form = self.form_size_category_add()
        self.data_context['form'] = form
        return render(request, self.template, self.data_context)

    def post(self, request):
        brand = helper_session_brand_pk(request)
        form = self.form_size_category_add(request.POST)
        if form.is_valid():
            size_category = form.save(commit=False)
            size_category.user = request.user
            size_category.brand = brand
            size_category.status = True
            size_category.save()
            messages.success(request, 'Size Category successfully added')
            return HttpResponseRedirect(reverse('aplinventory:size_add', 
                                        kwargs={'pk_sizecategory': size_category.pk}))

        self.data_context['form'] = form
        return render(request, self.template, self.data_context)


class SizeCategoryChange(View):
    form_size_category_change = FormSizeCategoryChange
    data_context = {}
    template = 'aplinventory/sizecategory/sizecategory_change.html'

    @method_decorator(login_required)
    @method_decorator(connecting_brand_required)
    def dispatch(self, *args, **kwargs):
        return super(SizeCategoryChange, self).dispatch(*args, **kwargs)

    def get(self, request, size_category_pk):
        brand = helper_session_brand_pk(request)
        size_category = get_object_or_404(SizeCategory, pk=size_category_pk)
        form = self.form_size_category_change(instance=size_category)
        self.data_context['form'] = form
        self.data_context['size_category'] = size_category
        return render(request, self.template, self.data_context)

    def post(self, request, size_category_pk):
        brand = helper_session_brand_pk(request)
        size_category = get_object_or_404(SizeCategory, pk=size_category_pk)
        form = self.form_size_category_change(instance=size_category, data=request.POST)

        if form.is_valid():
            size_category = form.save(commit=False)
            size_category.user = request.user
            size_category.save()
            messages.success(request, 'Size Category successfully changed.')
            return HttpResponseRedirect(reverse('aplinventory:sizecategory_list'))

        self.data_context['size_category'] = size_category
        self.data_context['form'] = form
        return render(request, self.template, self.data_context)


class SizeCategoryRemove(View):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SizeCategoryRemove, self).dispatch(*args, **kwargs)

    def get(self, request, size_category_pk):
        size_category = get_object_or_404(SizeCategory, pk=size_category_pk)

        if size_category.size_set.exists():
            messages.error(request, 'Size Category cannot delete.')
        else:
            size_category.delete()
            messages.success(request, 'Size Category successfully removed.')

        return HttpResponseRedirect(reverse('aplinventory:sizecategory_list'))

class SizeList(View):
    data_context = {}
    template = 'aplinventory/size/size_list.html'

    @method_decorator(login_required)
    @method_decorator(connecting_brand_required)
    def dispatch(self, *args, **kwargs):
        return super(SizeList, self).dispatch(*args, **kwargs)


@connecting_brand_required
def size_list(request):
    brand = helper_session_brand_pk(request)
    sizes = Size.objects.all()
    data_context = {'sizes': sizes}
    return render(request, 'aplinventory/size/size_list.html', data_context)


@connecting_brand_required
def size_add(request, pk_sizecategory):
    brand = helper_session_brand_pk(request)
    sizecategory = get_object_or_404(SizeCategory, pk=pk_sizecategory)
    sizes = Size.objects.filter(size_category=sizecategory)
    if request.method == 'POST':
        form = FormAddSize(data=request.POST)
        if form.is_valid():
            size = form.save(commit=False)
            size.user = request.user
            size.brand = brand
            size.size_category = sizecategory

            # Handling size same. integrity error ...
            try:
                size.save()
                messages.success(request, 'Size successfully added')
            except IntegrityError:
                messages.warning(request, 'Size not be same !')

            return HttpResponseRedirect(reverse('aplinventory:size_add',
                                                kwargs={'pk_sizecategory': pk_sizecategory}))
    else:
        form = FormAddSize()

    data_context = {'form': form, 'sizecategory': sizecategory, 'sizes': sizes}
    return render(request, 'aplinventory/size/size_add.html', data_context)


@connecting_brand_required
def size_change(request, pk_size):
    size = get_object_or_404(Size, pk=pk_size)

    if request.method == 'POST':
        form = FormChangeSize(data=request.POST, instance=size)
        if form.is_valid():
            size_frm = form.save(commit=False)
            size_frm.user = request.user
            size_frm.save()
            messages.success(request, 'Size successfully changed')
            return HttpResponseRedirect(reverse('aplinventory:sizecategory_list'))
    else:
        form = FormChangeSize(instance=size)

    data_context = {'form': form, 'size': size}
    return render(request, 'aplinventory/size/size_change.html', data_context)


@connecting_brand_required
def size_remove(request, pk_size):
    size = get_object_or_404(Size, pk=pk_size)
    if size.articledetail_set.count() > 0:
        messages.error(request, 'Size Cannot delete or update a parent row: a foreign key constaint fails.')
    else:
        size.delete()
        messages.success(request, 'Size successfully removed')
    return HttpResponseRedirect(reverse('aplinventory:sizecategory_list'))


@connecting_brand_required
def productcategory_list(request):
    productcategories = ProductCategory.objects.all()
    data_context = {'productcategories': productcategories}
    return render(request, 'aplinventory/productcategory/productcategory_list.html', data_context)


@connecting_brand_required
def productcategory_add(request):
    brand = helper_session_brand_pk(request)
    if request.method == 'POST':
        form = FormAddProductCategory(brand, request.POST)
        if form.is_valid():
            productcategory = form.save(commit=False)
            productcategory.user = request.user
            productcategory.brand = brand
            productcategory.save()
            messages.success(request, 'Product category successfully added')
            return HttpResponseRedirect(reverse('aplinventory:productcategory_list'))
    else:
        form = FormAddProductCategory(brand)

    data_context = {'form': form}
    return render(request, 'aplinventory/productcategory/productcategory_add.html', data_context)


@connecting_brand_required
def productcategory_change(request, pk_productcategory):
    productcategory = get_object_or_404(ProductCategory,
                                        pk=pk_productcategory)

    brand = productcategory.brand

    if request.method == 'POST':
        form = FormChangeProductCategory(brand, data=request.POST,
                                         instance=productcategory)
        if form.is_valid():
            productcategory_frm = form.save(commit=False)

templates/aplinventory/article/article_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Add Article{% endblock %}

{% block heading %}Add Article{% endblock %}

{% block content %}
<div class="col-lg-12">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="{{ form.product.id_for_label }}">Product :</label>
            {{ form.product|add_class:'form-control' }}
            {% if form.product.errors %}
                {% for error in form.product.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name :</label>
            {{ form.name|add_class:'form-control' }}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.capital_price.id_for_label }}">Capital Price :</label>
            {{ form.capital_price|add_class:'form-control' }}
            {% if form.capital_price.errors %}
                {% for error in form.capital_price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.price.id_for_label }}" >Price (IDR) :</label>
            {{ form.price|add_class:'form-control'|attr:"onfocus:notifyMe();" }}
            {% if form.price.errors %}
                {% for error in form.price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <input type="submit"  value="save" class="btn btn-success">
    </form>
</div>
{% endblock %}

templates/aplinventory/article/article_change.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Change Article{% endblock %}

{% block heading %}Change Article{% endblock %}

{% block content %}
<div class="col-lg-12">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name :</label>
            {{ form.name|add_class:'form-control' }}
            {% if form.name.errors %}
                {% for error in form.name.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.capital_price.id_for_label }}">Capital Price (IDR) :</label>
            {{ form.capital_price|add_class:'form-control' }}
            {% if form.capital_price.errors %}
                {% for error in form.capital_price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.price.id_for_label }}">Price (IDR) :</label>
            {{ form.price|add_class:'form-control' }}
            {% if form.price.errors %}
                {% for error in form.price.errors %}
                    <span class="help-block text-danger">{{ error|escape }}</span>
                {% endfor %}
            {% endif %}
        </div>
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/aplinventory/article/article_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Article{% endblock %}

{% block heading %}Article{% endblock %}

{% block content %}
<div class="col-lg-6">
    <a href="{% url 'aplinventory:article_add' %}">add new</a>
</div>
<div class="col-lg-6">
    <form action="" class="form-horizontal">
        <input type="text" name="query" class="form-control" placeholder="Search Article">
    </form>
</div>
<br>
<div class="col-lg-12">
    <table class="table table-striped table-condensed">
        <tr>
            <th>#</th>
            <th>User</th>
            <th>Code</th>
            <th>Brand</th>
            <th>Product</th>
            <th>Name</th>
            <th>Capital Price</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
        {% for article in articles %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ article.user.username }}</td>
            <td>{{ article.code }}</td>
            <td>
                <span class="label label-info">{{ article.brand.name }}</span>
            </td>
            <td>{{ article.product }}</td>
            <td id="id_article_name" data-toggle="modal" data-target="#{{ article.code }}"><a href="#">{{ article.name }}</a></td>
            <td>{{ article.capital_price }}</td>
            <td>{{ article.price }}</td>
            <td>
                <a href="{% url 'aplinventory:article_change' article.pk %}">change</a> |
                <a href="{% url 'aplinventory:article_remove' article.pk %}">remove</a>

                {# modal dialog article detail #}
                <div class="modal fade bs-example-modal-lg" id="{{ article.code }}" tabindex="-1" role="dialog" >
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">{{ article.name }}</h4>
                            </div>
                            <div class="modal-body">
                                <a href="{% url 'aplinventory:articledetail_add' article.pk article.product.product_category.sizecategory.pk %}">open</a>
                                <br><br>
                                <table class="table table-condensed table-striped">
                                    <tr>
                                        <th>#</th>
                                        <th>Code</th>
                                        <th>Size</th>
                                        <th>Stock</th>
                                    </tr>
                                    {% for articledetail in article.articledetail_set.all %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ articledetail.code }}</td>
                                            <td>{{ articledetail.size }}</td>
                                            <td>{{ articledetail.stock }}</td>
                                        </tr>
                                    {% empty %}
                                        <tr>
                                            <td colspan="5">Empty</td>
                                        </tr>
                                    {% endfor %}
                                </table> 
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <a target="_blank" href="{% url 'aplinventory:article_printbarcode' article.code %}" class="btn btn-info">barcode</a>
                             
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="9">Your article has not added.</td>
        </tr>
        {% endfor %}
    </table>
</div>

<div class="col-md-12">
    {% include "aplinventory/article/pagination.html" with page=articles query=query %}
</div>
{% endblock %}

templates/aplinventory/article/article_printbarcode.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>HTML & CSS Avery Labels (5160) by MM at Boulder Information Services</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/article_printbarcode.css' %}">
</head>
<body>


{% for ad in article.articledetail_set.all %}
    {% for i in ""|ljust:ad.stock %}
    <div class="label">
        <span>IDR {{ article.price }} {{ article.name }} ({{ ad.size }})</span>
        <div id="{{article.code}}_{{ ad.code }}_{{ ad.stock }}_{{ forloop.counter }}" data-code="{{ ad.code }}">
        <script>
            $("#{{article.code}}_{{ ad.code }}_{{ ad.stock }}_{{ forloop.counter }}")
                .barcode("{{ ad.code }}", "code93", 
                    {
                        barWidth: 2 , 
                        barHeight: 60,
                        output: "css",
                        fontSize: 10,
                        marginHRI: 12,
                        showHRI: false}); 
        </script>
        </div>
        <span>{{ ad.code }}</span>
    </div>
    <div class="page-break"></div>
    {% endfor %}
{% endfor %}

<!-- JQUERY -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bower_components/simplebarcode/jquery-barcode.js' %}"></script>

</body>
</html>