aplbillship/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^billing/(?P<invoice_number>[\w\-]+)/add\.html$', views.billing_add, name='billing_add'),
    url(r'^billing/(?P<invoice_number>[\w\-]+)/(?P<code>[\w\-]+)/remove\.html$', views.billing_remove, name='billing_remove'),

    url(r'^shipping/(?P<invoice_number>[\w\-]+)/add\.html$', views.shipping_add, name='shipping_add'),
    url(r'^shipping/(?P<invoice_number>[\w\-]+)/(?P<code>[\w\-]+)/remove\.html$', views.shipping_remove, name='shipping_remove'),
]

aplinventory/urls.py
from django.conf.urls import url
from . import views
from . import views_popup
from . import urls_ajax

urlpatterns = [

    # SizeType URL
    url(r'^sizecategory\.html$', views.SizeCategoryList.as_view(), name='sizecategory_list'),
    url(r'^sizecategory/add\.html$', views.SizeCategoryAdd.as_view(), name='sizecategory_add'),
    url(r'^sizecategory/(?P<size_category_pk>[0-9]+)/change\.html$', views.SizeCategoryChange.as_view(), name='sizecategory_change'),
    url(r'^sizecategory/(?P<size_category_pk>[0-9]+)/remove\.html$', views.SizeCategoryRemove.as_view(), name='sizecategory_remove'),

    # # Size URL
    url(r'size\.html$', views.size_list, name='size_list'),
    url(r'size/(?P<pk_sizecategory>[0-9]+)/add\.html$', views.size_add, name='size_add'),
    url(r'size/(?P<pk_size>[0-9]+)/change\.html$', views.size_change, name='size_change'),
    url(r'size/(?P<pk_size>[0-9]+)/removed\.html$', views.size_remove, name='size_remove'),

    # Product Category URL
    url(r'^productcategory/$', views.productcategory_list, name='productcategory_list'),
    url(r'^productcategory/add/$', views.productcategory_add, name='productcategory_add'),
    url(r'^productcategory/(?P<pk_productcategory>[0-9]+)/change/$', views.productcategory_change, name='productcategory_change'),
    url(r'^productcategory/(?P<pk_productcategory>[0-9]+)/remove/$', views.productcategory_remove, name='productcategory_remove'),

    # Product URL
    url(r'^product/$', views.product_list, name='product_list'),
    url(r'^product/add/$', views.product_add, name='product_add'),
    url(r'^product/(?P<code_product>[\w\-]+)/change/$', views.product_change, name='product_change'),
    url(r'^product/(?P<code_product>[\w\-]+)/remove/$', views.product_remove, name='product_remove'),

    # Article URL
    url(r'^article/$', views.article_list, name='article_list'),
    url(r'^article/add/$', views.article_add, name='article_add'),
    url(r'^article/(?P<pk_article>[0-9]+)/change/$', views.article_change, name='article_change'),
    url(r'^article/(?P<pk_article>[0-9]+)/remove/$', views.article_remove, name='article_remove'),
    url(r'^article/(?P<pk_article>[0-9]+)/keep/$', views.article_keep, name='article_keep'),
    url(r'^article/(?P<code>[\w\-]+)/print/barcode.pdf/$', views.article_printbarcode, name='article_printbarcode'),
    
    # ArticleDetail URL
    url(r'^articledetail/(?P<pk_article>[0-9]+)/(?P<pk_sizecategory>[0-9]+)/add/$',
        views.articledetail_add, name='articledetail_add'),
    url(r'^articledetail/(?P<pk_article>[0-9]+)/(?P<pk_articledetail>[0-9]+)/change/$', 
        views.articledetail_change, name='articledetail_change'),
    url(r'^articledetail/(?P<code>[\w\-]+)/remove/$',
        views.articledetail_remove, name='articledetail_remove'),

    # ArticleDetail Popup URL
    url(r'^popup/articledetail/', views_popup.articledetail_list_popup, name='articledetail_list_popup'),

    #
    # # ArticleDetail POPUP URL
    # url(r'articledetail/popup/$', views.articledetail_list_popup, name='articledetail_list_popup'),
]

apltransaction/urls.py
from django.conf.urls import url
from . import views, ajax_views

urlpatterns = [

    url(r'^ajax/invoice/remove/hold/invalid\.html', views.ajax_invoice_remove_hold_and_invalid, name='ajax_invoice_remove_hold_and_invalid'),

    # Invoice Store URL
    url(r'^invoice/store\.html$', views.invoicestore_list, name='invoicestore_list'),
    url(r'^invoice/store/add\.html$', views.invoicestore_add, name='invoicestore_add'),
    url(r'^invoice/store/(?P<invoice_number>[\w\-]+)/print\.html$', views.invoicestore_print, name='invoicestore_print'),
    url(r'^invoice/store/(?P<invoice_number>[\w\-]+)/remove\.html$', views.invoicestore_remove, name='invoicestore_remove'),
    
    # Transaction Store URL
    url(r'^transdetail/store/(?P<invoice_number>[\w\-]+)/add\.html$', views.transactiondetailstore_add, name='transactiondetailstore_add'),
    url(r'^transdetail/store/(?P<invoice_number>[\w\-]+)/(?P<article_code>[\w\-]+)/remove\.html$', views.transactiondetailstore_remove, name='transactiondetailstore_remove'),

    # Invoice Web URL
    url(r'^invoice/web\.html$', views.invoiceweb_list, name='invoiceweb_list'),
    url(r'^ajax/invoice/web\.html$', ajax_views.AjaxInvoiceWebList.as_view(), name='ajax_invoice_web_list'),
    url(r'^invoice/web/add\.html$', views.invoiceweb_add, name='invoiceweb_add'),
    url(r'^invoice/web/(?P<invoice_number>[\w\-]+)/remove\.html$', views.invoiceweb_remove, name='invoiceweb_remove'),
    url(r'^invoice/web/(?P<invoice_number>[\w\-]+)/print\.html$', views.invoiceweb_print, name='invoiceweb_print'),
    url(r'^invoice/web/(?P<invoice_number>[\w\-]+)/changestatus\.html$', views.invoiceweb_changestatus, name='invoiceweb_changestatus'),
    url(r'^invoice/web/print/all\.html$', views.invoiceweb_print_all, name="invoiceweb_print_all"),
    url(r'^invoice/web/change/status/process\.html', views.invoiceweb_change_status_process, name='invoiceweb_change_status_process'),
    url(r'^invoice/web/change/status/ready\.html', views.invoiceweb_change_status_ready, name="invoiceweb_change_status_ready"),
    url(r'^invoice/web/change/status/pending\.html', views.invoiceweb_change_status_pending, name="invoiceweb_change_status_pending"),
    url(r'^invoice/web/change/status/finish\.html', views.invoiceweb_change_status_finish, name="invoiceweb_change_status_finish"),
    url(r'^invoice/web/change/status/cancel\.html', views.invoiceweb_change_status_cancel, name="invoiceweb_change_status_cancel"),
    
    # ==========================
    # Transaction Detail Web URL
    # ==========================
    url(r'^transdetail/web/(?P<invoice_number>[\w\-]+)/add\.html$', views.transactiondetailweb_add, name='transactiondetailweb_add'),
    url(r'^transdetail/web/(?P<invoice_number>[\w\-]+)/(?P<article_code>[\w\-]+)/remove\.html$', views.transactiondetailweb_remove, name='transactiondetailweb_remove'),


]

dms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^base/', include('aplbase.urls', namespace='aplbase')),
    url(r'^distro/', include('apldistro.urls', namespace='apldistro')),
    url(r'^inventory/', include('aplinventory.urls', namespace='aplinventory')),
    url(r'^transaction/', include('apltransaction.urls', namespace="apltransaction")),
    url(r'', include('aplaccount.urls', namespace='aplaccount')),
    url(r'^billship/', include('aplbillship.urls', namespace='aplbillship')),
    url(r'^report/', include('aplreport.urls', namespace='aplreport')),
    url(r'^promotion/', include('aplpromotion.urls', namespace='aplpromotion')),
    url(r'^admin/', include(admin.site.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apltransaction/models.py
from django.db import models
from apldistro.models import Brand
from aplinventory.models import ArticleDetail
import datetime

class InvoiceCategory(models.Model):
    abbv = models.CharField(max_length=2)
    info = models.CharField(max_length=30)

    def __str__(self):
        return self.abbv


class InvoiceStatus(models.Model):
    abbv = models.CharField(max_length=2)
    info = models.CharField(max_length=30)

    def __str__(self):
        return self.abbv


class Invoice(models.Model):
    user = models.ForeignKey('auth.User')
    invoice_number = models.CharField(max_length=10, unique=True)
    invoice_date = models.DateField(default=datetime.date.today)
    total = models.PositiveIntegerField()
    category = models.ForeignKey(InvoiceCategory)
    status = models.ForeignKey(InvoiceStatus)

    def __str__(self):
        return self.invoice_number


class TransactionDetail(models.Model):
    user = models.ForeignKey('auth.User')
    invoice = models.ForeignKey(Invoice)

    article_brand_code = models.CharField(max_length=30)
    article_brand_name = models.CharField(max_length=100)
    article_code = models.CharField(max_length=200)
    article_name = models.CharField(max_length=200)
    article_size = models.CharField(max_length=50)
    article_price = models.PositiveIntegerField()
    article_capitalprice = models.PositiveIntegerField()

    quantity = models.PositiveIntegerField()
    sub_total = models.PositiveIntegerField()
    
    ################ DISCOUNT AREA #########################################
    discount_code = models.CharField(max_length=100, blank=True, null=True)
    discount_name = models.CharField(max_length=30, blank=True, null=True)
    cut_price = models.PositiveIntegerField(blank=True, null=True)
    ########################################################################

    def __str__(self):
        return self.invoice.invoice_number

    class Meta:
        unique_together = ('invoice', 'article_size', 'article_code')

apltransaction/forms.py
from django import forms
from .models import Invoice, TransactionDetail


class FormAddTransactionDetail(forms.ModelForm):
    class Meta:
        model = TransactionDetail
        fields = ('article_code', 'article_name', 'article_size',
                  'article_price', 'quantity', 'sub_total')


class FormAddTransactionStoreDetail(forms.ModelForm):
	class Meta:
		model = TransactionDetail
		fields = ('article_code',)


class FormAddTransactionWebDetail(forms.ModelForm):
    class Meta:
        model = TransactionDetail
        fields = ('article_code', 'article_name', 'article_size',
                  'article_price', 'quantity', 'sub_total')


class FormSearchInvoice(forms.Form):
    query = forms.CharField()


class FormInvoiceWebChangeStatus(forms.ModelForm):
  class Meta:
    model = Invoice
    fields = ('status',)

templates/apltransaction/transactiondetail/transactiondetailstore_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Invoice In Store{% endblock %}

{% block heading %}Invoice In Store{% endblock %}

{% block content %}
<div class="col-md-12">
    <table class="table table-bordered">
        <tr>
            <th>Number</th>
            <th>User</th>
            <th>Date</th>
            <th>Total</th>
            <th>Category</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>{{ invoice.invoice_number }}</td>
            <td>{{ invoice.user }}</td>
            <td>{{ invoice.invoice_date }}</td>
            <td>{{ invoice.total }}</td>
            <td>{{ invoice.category.info }}</td>
            <td>
                <a href="{% url 'apltransaction:invoicestore_remove' invoice.invoice_number %}" class="btn btn-danger">
                <i class="fa fa-minus-circle"></i> Abort
                </a>
                <a href="{% url 'apltransaction:invoicestore_print' invoice.invoice_number %}" class="btn btn-default">
                    <i class="fa fa-print"></i> Print
                </a>
            </td>
        </tr>
        <tr>
            <td colspan="6">
                <form action="" method="post" class="">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    {{ form.article_code|add_class:'form-control'|attr:'onclick:openShowArticle();'|attr:'placeholder:Choose'}}
                    {% if form.article_code.errors %}
                        {% for error in form.article_code.errors %}
                            <span class="help-block text-warning">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </form>
            </td>
        </tr>
    </table>
</div>

<br>

<div class="col-md-12">
    <table class="table table-bordered">
        <tr>
            <th colspan="8" class="text-center">Article In Bag</th>
        </tr>
        <tr>
            <th>#</th>
            <th>Code</th>
            <th>Name</th>
            <th>Size</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Sub Total</th>
            <th>Action</th>
        </tr>
        {% for trandet in transactiondetails %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ trandet.article_code }}</td>
                <td>{{ trandet.article_name }}</td>
                <td>{{ trandet.article_size }}</td>
                <td>{{ trandet.article_price }}
                    {% if trandet.discount_code %}
                        <small>
                            <br> Cut Price (Discount):
                            <br> {{ trandet.discount_name }} ({{ trandet.cut_price }}) per item
                        </small>
                    {% endif %}
                </td>
                <td>{{ trandet.quantity }}</td>
                <td>{{ trandet.sub_total }}</td>
                <td>
                    <a href="{% url 'apltransaction:transactiondetailstore_remove' invoice.invoice_number trandet.article_code %}" class="text-danger">
                        remove
                    </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="8">Empty Transaction Detail</td>
            </tr>
        {% endfor %}
    </table>
</div>


{% endblock %}


{% block js %}
<script>
    $("#id_article_code").focus();
</script>
{% endblock %}

templates/apltransaction/transactiondetail/transactiondetailweb_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Invoice In Web{% endblock %}

{% block heading %}Invoice In Web{% endblock %}

{% block content %}
<div class="col-md-6">
    <table class="table table-bordered">
        <tr>
            <th colspan="2" class="text-center">Invoice Information</th>
        </tr>
        <tr>
            <th>User</th>
            <td>{{ invoice.user }}</td>
        </tr>
        <tr>
            <th>Invoice Number</th>
            <td>{{ invoice.invoice_number }}</td>
        </tr>
        <tr>
            <th>Invoice Date</th>
            <td>{{ invoice.invoice_date }}</td>
        </tr>
        <tr>
            <th>Total</th>
            <td>{{ invoice.total }}</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>{{ invoice.category.info }}</td>
        </tr>
        <tr>
            <th>Status</th>
            <td>
                {{ invoice.status.info }}
                
            </td>
        </tr>
        <tr>
            <th>Action</th>
            <td>
                <a class="btn btn-default" href="{% url 'apltransaction:invoiceweb_remove' invoice.invoice_number %}" class="text-danger">
                    remove
                </a>
                <a class="btn btn-default" href="{% url 'apltransaction:invoiceweb_changestatus' invoice.invoice_number %}">
                    change
                </a>
                <a class="btn btn-default" href="{% url 'apltransaction:invoiceweb_print' invoice.invoice_number %}">
                    print
                </a>
            </td>
        </tr>
    </table>
</div>

<div class="col-md-6">
    <form action="" method="post" class="">
    {% csrf_token %}
        {{ form.non_field_errors }}
        <table class="table table-bordered">
            <tr>
                <th colspan="2" class="text-center">Form Add Article</th>
            </tr>
            {# transactiondetail article_code field #}
            <tr>
                <td><label for="{{ form.article_code.id_for_label }}">Code</label></td>
                <td>
                    {{ form.article_code|add_class:'form-control'|attr:'onclick:openShowArticle();'|attr:'placeholder:Choose'}}
                    {% if form.article_code.errors %}
                        {% for error in form.article_code.errors %}
                            <span class="help-block text-warning">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
            {# transactiondetail article_name field #}
            <tr>
                <td><label for="{{ form.article_name.id_for_label }}">Name</label></td>
                <td>
                    {{ form.article_name|add_class:'form-control' }}
                    {% if form.article_name.errors %}
                        {% for error in form.article_name.errors %}
                            <span class="help-block text-warning">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><label for="{{ form.article_size.id_for_label }}">Size</label></td>
                <td>
                    {{ form.article_size|add_class:'form-control' }}
                    {% if form.article_size.errors %}
                        {% for error in form.article_size.errors %}
                            <span class="help-block text-warning">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><label for="{{ form.article_price.id_for_label }}">Price</label></td>
                <td>
                    {{ form.article_price|add_class:'form-control' }}
                    {% if form.article_price.errors %}
                        {% for error in form.article_price.errors %}
                            <span class="help-block text-warning">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><label for="{{ form.quantity.id_for_label }}">Quantity</label></td>
                <td>
                    {{ form.quantity|add_class:'form-control' }}
                    {% if form.quantity.errors %}
                        {% for error in form.quantity.errors %}
                            <span class="help-block text-warning">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><label for="{{ form.sub_total.id_for_label }}">Sub Total</label></td>
                <td>
                    {{ form.sub_total|add_class:'form-control' }}
                    {% if form.sub_total.errors %}
                        {% for error in form.sub_total.errors %}
                            <span class="help-block text-warning">{{ error|escape }}</span>
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td colspan="2" class="">
                    <input type="submit" value="add" class="btn btn-success pull-right">
                </td>
            </tr>
        </table>
    </form>
</div>
<br>

{# ITEM TRANSACTION DETAIL #}
<div class="col-md-12">
    <table class="table table-bordered">
        <tr>
            <th colspan="9" class="text-center">Article In Bag</th>
        </tr>
        <tr>
            <th>#</th>
            <th>Brand</th>
            <th>Code</th>
            <th>Name</th>
            <th>Size</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Sub Total</th>
            <th>Action</th>
        </tr>
        {% for trandet in transactiondetails %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ trandet.article_brand_name }}</td>
                <td>{{ trandet.article_code }}</td>
                <td>{{ trandet.article_name }}</td>
                <td>{{ trandet.article_size }}</td>
                <td>
                    {{ trandet.article_price }}
                    {% if trandet.discount_code %}
                    <small>
                        <br> Discount 
                        <br> {{ trandet.discount_name }} ({{ trandet.cut_price }}) per item
                    </small>
                    {% endif %}
                </td>
                <td>{{ trandet.quantity }}</td>
                <td>{{ trandet.sub_total }}</td>
                <td>
                    <a href="{% url 'apltransaction:transactiondetailweb_remove' invoice.invoice_number trandet.article_code %}" class="text-danger">
                        remove
                    </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="9">Empty Transaction Detail</td>
            </tr>
        {% endfor %}
    </table>
</div>
<br>
<div class="col-md-12">
    <table class="table table-bordered">
        <tr>
            <th colspan="6" class="text-center">Billing</th>
        </tr>
        <tr>
            <th>Code</th>
            <th>Invoice Number</th>
            <th>Customer Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Action</th>
        </tr>
        {% if billing %}
        <tr>
            <td>{{ billing.code }}</td>
            <td>{{ billing.invoice.invoice_number }}</td>
            <td>{{ billing.name }}</td>
            <td>{{ billing.email }}</td>
            <td>{{ billing.phone }}</td>
            <td>
                <a class="text-danger" href="{% url 'aplbillship:billing_remove' invoice.invoice_number billing.code %}">
                    remove
                </a>
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="6">
                Please, add your billing 
                <a class="text-primary" href="{% url 'aplbillship:billing_add' invoice.invoice_number %}">
                    add
                </a>
            </td>
        </tr>
        {% endif %}
    </table>
</div>

<br>

<div class="col-md-12">
    <table class="table table-bordered">
        <tr>
            <th colspan="8" class="text-center">Shipping</th>
        </tr>
        <tr>
            <th>Code</th>
            <th>Invoice Number</th>
            <th>Province</th>
            <th>City</th>
            <th>Vendor / Courier</th>
            <th>Package</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
        {% if shipping %}
        <tr>
            <td>{{ shipping.code }}</td>
            <td>{{ shipping.invoice.invoice_number }}</td>
            <td>{{ shipping.province }}</td>
            <td>{{ shipping.city }}</td>
            <td>{{ shipping.vendor }}</td>
            <td>{{ shipping.pack }}</td>
            <td>{{ shipping.price }}</td>
            <td>
                <a class="text-danger" href="{% url 'aplbillship:shipping_remove' invoice.invoice_number shipping.code %}">
                    remove
                </a>
            </td>
        </tr>
        <tr>
            <td colspan="8">
                <strong>Address:</strong> <br>
                {{ shipping.address }}
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="8">
                Please, add your shipping 
                <a href="{% url 'aplbillship:shipping_add' invoice.invoice_number %}" class="text-primary">
                    add
                </a>
            </td>
        </tr>
        {% endif %}
    </table>
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'sbadmin/vendor/coderain/coderain.js' %}"></script>
    <script>
        function openShowArticle() {
            window.open(
                    "{% url 'aplinventory:articledetail_list_popup' %}",
                    "Ratting",
                    "width=750,height=300,left=600,top=100,toolbar=0,status=1,resizable=no,scrollbars=no,");
        }

        $('document').ready(function () {

            $('#id_quantity').change(function(e) {
                var price = parseInt($("#id_article_price").val());
                var quantity = parseInt($(this).val());
                $("#id_sub_total").val(price * quantity);
            });
        });
    </script>
{% endblock %}